/*Таблица рейтикнга MPA
  хранит id и название рейтинга */
CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id int PRIMARY KEY,
    name   varchar(40)     NOT NULL,
    CONSTRAINT mpa_pk PRIMARY KEY (mpa_id)

);
/*Таблица фильмов одна из остновных таблиц
  id, имя,описание, дату редиза, длительность, и рейтинг фильма*/
CREATE TABLE IF NOT EXISTS film
(
    film_id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(40)                          NOT NULL,
    description  varchar  (1000)                      NOT NULL,
    release_date date                                 NOT NULL,
    duration     int                                  NOT NULL,
    mpa_id       int                                  NOT NULL,
    CONSTRAINT film_pk PRIMARY KEY (film_id),
    CONSTRAINT mpa_fk FOREIGN KEY (mpa_id) REFERENCES mpa

);

/*Таблица жанров
  хранит id и название жанра*/
CREATE TABLE IF NOT EXISTS genre
(
    genre_id int  PRIMARY KEY,
    name     varchar(40)      NOT NULL,
    CONSTRAINT genre_pk PRIMARY KEY (genre_id)

);

/*Таблица связей фильма и жанра
  хранит id связи  id фильма и id  жанра */
CREATE TABLE IF NOT EXISTS film_genre
(
    film_genre_id int  as concat(film_id,genre_id) PRIMARY KEY,
    film_id  int NOT NULL,
    genre_id int NOT NULL,
    CONSTRAINT film_genre_id_pk PRIMARY KEY (film_genre_id),
    CONSTRAINT film_genre_film_fk FOREIGN KEY (film_id) REFERENCES film ON DELETE CASCADE,
    CONSTRAINT film_genre_genre_fk FOREIGN KEY (genre_id) REFERENCES genre
);

/*Таблица пользователей
  хранит id пользователя, логин, имя, почту и дату рождения */
CREATE TABLE IF NOT EXISTS users
(
    user_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login    varchar(40)                              NOT NULL,
    name     varchar (40)                             NOT NULL,
    email    varchar (40)                             NOT NULL,
    birthday date                                     NOT NULL,
    CONSTRAINT user_pk PRIMARY KEY (user_id)
);

/*Таблица связей фильма и пользовтеля поставившего лайк
  хранит id связи  id фильма и id  пользователя */
CREATE TABLE IF NOT EXISTS film_likes
(
    film_likes_id int as concat(film_id,user_id) PRIMARY KEY,
    film_id int NOT NULL,
    user_id int NOT NULL,
    CONSTRAINT film_likes_id_pk PRIMARY KEY (film_likes_id),
    CONSTRAINT film_like_film_fk FOREIGN KEY (film_id) REFERENCES film ON DELETE CASCADE,
    CONSTRAINT film_like_user_fk FOREIGN KEY (user_id) REFERENCES users ON DELETE CASCADE
);

/*Таблица связей пользователей
  хранит id связи  id пользователя  и id друга пользователя  */
CREATE TABLE IF NOT EXISTS user_friend
(
    user_friend_id int as concat(user_id,friend_id)PRIMARY KEY,
    user_id   int NOT NULL,
    friend_id int NOT NULL,
    CONSTRAINT user_friend_pk PRIMARY KEY (user_friend_id),
    CONSTRAINT user_friend_user_fk FOREIGN KEY (user_id) REFERENCES users ON DELETE CASCADE,
    CONSTRAINT user_friend_friend_fk FOREIGN KEY (friend_id) REFERENCES users ON DELETE CASCADE
);

/*Таблица отзывов
  хранит id отзыва, содержание, оценку фильму положительную или отрицательную,
  id пользователя который оставил отзыв  и id фильма */
CREATE TABLE IF NOT EXISTS reviews
(
    review_id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content        varchar(1000)                     NOT NULL,
    is_positive    boolean                           ,
    user_id        int                               NOT NULL,
    film_id        int                               NOT NULL,
    CONSTRAINT user_fk FOREIGN KEY (user_id) REFERENCES users ON DELETE CASCADE,
    CONSTRAINT film_fk FOREIGN KEY (film_id) REFERENCES film ON DELETE CASCADE
);

/*Таблица связей  отзыва и пользователя посчитавшего отзыв полезным
  хранит id связи  id отзыва  и id  пользователя  */
CREATE TABLE IF NOT EXISTS review_like
(
    review_like_id int AS concat(review_id,user_id) PRIMARY KEY,
    review_id      int                               NOT NULL,
    user_id        int                               NOT NULL,
    CONSTRAINT review_like_fk FOREIGN KEY (review_id) REFERENCES reviews ON DELETE CASCADE,
    CONSTRAINT user_review_like_fk FOREIGN KEY (user_id) REFERENCES users ON DELETE CASCADE
    );

/*Таблица связей  отзыва и пользователя посчитавшего отзыв бесполезным
  хранит id связи  id отзыва  и id  пользователя  */
CREATE TABLE IF NOT EXISTS review_dislike
(
    review_dislike_id int AS concat(review_id,user_id) PRIMARY KEY,
    review_id      int                               NOT NULL,
    user_id        int                               NOT NULL,
    CONSTRAINT review_dislike_fk FOREIGN KEY (review_id) REFERENCES reviews ON DELETE CASCADE,
    CONSTRAINT user_review_dislike_fk FOREIGN KEY (user_id) REFERENCES users ON DELETE CASCADE
);

/*Таблица режесеров
  хранит id и имя режесера */
CREATE TABLE IF NOT EXISTS director
(
    director_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   varchar(40)     NOT NULL,
    CONSTRAINT director_pk PRIMARY KEY (director_id)
);
/*Таблица связей фильмов и режесеров
  хранит id связи  id фильма  и id режесера */
CREATE TABLE IF NOT EXISTS film_director
(
    film_director_id int  as concat(film_id,director_id) PRIMARY KEY,
    film_id  int NOT NULL,
    director_id int NOT NULL,
    CONSTRAINT film_director_id_pk PRIMARY KEY (film_director_id),
    CONSTRAINT film_director_film_fk FOREIGN KEY (film_id) REFERENCES film ON DELETE CASCADE,
    CONSTRAINT film_director_director_fk FOREIGN KEY (director_id) REFERENCES director ON DELETE CASCADE
);
/*Таблица событий
  хранит id сыбытия, id пользователя , id объекта , тип объекта, тип  события, операцию, и время события */
CREATE TABLE IF NOT EXISTS event
(
    event_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL,
    entity_id int NOT NULL,
    entity_type varchar NOT NULL,
    event_type varchar NOT NULL,
    operation varchar NOT NULL,
    created_at timestamp DEFAULT NOW(),
    CONSTRAINT event_pk PRIMARY KEY (event_id),
    CONSTRAINT event_user_fk FOREIGN KEY (user_id) REFERENCES users ON DELETE CASCADE
);

